# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Simulated_Annealing.ui'
#
# Created: Sat Dec 01 12:59:35 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1139, 708)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.grp_out = QtGui.QGroupBox(self.centralwidget)
        self.grp_out.setGeometry(QtCore.QRect(570, 0, 560, 980))
        self.grp_out.setMinimumSize(QtCore.QSize(560, 980))
        self.grp_out.setMaximumSize(QtCore.QSize(560, 980))
        self.grp_out.setObjectName("grp_out")
        self.lbl_fp_info = QtGui.QLabel(self.grp_out)
        self.lbl_fp_info.setGeometry(QtCore.QRect(15, 553, 530, 417))
        self.lbl_fp_info.setText("")
        self.lbl_fp_info.setObjectName("lbl_fp_info")
        self.grp_box_FP_info = QtGui.QGroupBox(self.grp_out)
        self.grp_box_FP_info.setGeometry(QtCore.QRect(15, 23, 530, 100))
        self.grp_box_FP_info.setMinimumSize(QtCore.QSize(530, 100))
        self.grp_box_FP_info.setMaximumSize(QtCore.QSize(530, 100))
        self.grp_box_FP_info.setObjectName("grp_box_FP_info")
        self.lbl_utilize = QtGui.QLabel(self.grp_box_FP_info)
        self.lbl_utilize.setGeometry(QtCore.QRect(10, 63, 46, 16))
        self.lbl_utilize.setObjectName("lbl_utilize")
        self.lin_ar_rtio = QtGui.QLineEdit(self.grp_box_FP_info)
        self.lin_ar_rtio.setGeometry(QtCore.QRect(338, 30, 133, 20))
        self.lin_ar_rtio.setObjectName("lin_ar_rtio")
        self.lin_area = QtGui.QLineEdit(self.grp_box_FP_info)
        self.lin_area.setGeometry(QtCore.QRect(62, 30, 133, 20))
        self.lin_area.setObjectName("lin_area")
        self.lbl_time = QtGui.QLabel(self.grp_box_FP_info)
        self.lbl_time.setGeometry(QtCore.QRect(290, 60, 41, 16))
        self.lbl_time.setObjectName("lbl_time")
        self.lbl_area = QtGui.QLabel(self.grp_box_FP_info)
        self.lbl_area.setGeometry(QtCore.QRect(10, 30, 23, 16))
        self.lbl_area.setObjectName("lbl_area")
        self.lbl_ar_ratio = QtGui.QLabel(self.grp_box_FP_info)
        self.lbl_ar_ratio.setGeometry(QtCore.QRect(270, 30, 61, 16))
        self.lbl_ar_ratio.setObjectName("lbl_ar_ratio")
        self.lin_iter_num = QtGui.QLineEdit(self.grp_box_FP_info)
        self.lin_iter_num.setGeometry(QtCore.QRect(338, 63, 133, 20))
        self.lin_iter_num.setObjectName("lin_iter_num")
        self.lin_utilize = QtGui.QLineEdit(self.grp_box_FP_info)
        self.lin_utilize.setGeometry(QtCore.QRect(62, 63, 133, 20))
        self.lin_utilize.setObjectName("lin_utilize")
        self.grpbox_fp_sols = QtGui.QGroupBox(self.grp_out)
        self.grpbox_fp_sols.setGeometry(QtCore.QRect(10, 130, 530, 550))
        self.grpbox_fp_sols.setMinimumSize(QtCore.QSize(530, 550))
        self.grpbox_fp_sols.setMaximumSize(QtCore.QSize(530, 550))
        self.grpbox_fp_sols.setObjectName("grpbox_fp_sols")
        self.graph_view_sols = QtGui.QGraphicsView(self.grpbox_fp_sols)
        self.graph_view_sols.setGeometry(QtCore.QRect(10, 20, 510, 520))
        self.graph_view_sols.setMinimumSize(QtCore.QSize(510, 520))
        self.graph_view_sols.setMaximumSize(QtCore.QSize(510, 520))
        self.graph_view_sols.setObjectName("graph_view_sols")
        self.grp_init = QtGui.QGroupBox(self.centralwidget)
        self.grp_init.setGeometry(QtCore.QRect(0, 0, 560, 980))
        self.grp_init.setMinimumSize(QtCore.QSize(560, 980))
        self.grp_init.setMaximumSize(QtCore.QSize(560, 980))
        self.grp_init.setObjectName("grp_init")
        self.gridLayout_2 = QtGui.QGridLayout(self.grp_init)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.grpbox_fp = QtGui.QGroupBox(self.grp_init)
        self.grpbox_fp.setObjectName("grpbox_fp")
        self.graph_view_layout = QtGui.QGraphicsView(self.grpbox_fp)
        self.graph_view_layout.setGeometry(QtCore.QRect(10, 20, 530, 490))
        self.graph_view_layout.setMinimumSize(QtCore.QSize(530, 490))
        self.graph_view_layout.setMaximumSize(QtCore.QSize(530, 490))
        self.graph_view_layout.setObjectName("graph_view_layout")
        self.gridLayout_2.addWidget(self.grpbox_fp, 2, 0, 1, 3)
        self.lbl_inp_file = QtGui.QLabel(self.grp_init)
        self.lbl_inp_file.setObjectName("lbl_inp_file")
        self.gridLayout_2.addWidget(self.lbl_inp_file, 0, 0, 1, 1)
        self.btn_inp_file = QtGui.QPushButton(self.grp_init)
        self.btn_inp_file.setObjectName("btn_inp_file")
        self.gridLayout_2.addWidget(self.btn_inp_file, 0, 1, 1, 1)
        self.lin_cwd = QtGui.QLineEdit(self.grp_init)
        self.lin_cwd.setObjectName("lin_cwd")
        self.gridLayout_2.addWidget(self.lin_cwd, 0, 2, 1, 1)
        self.grp_box_sa_info = QtGui.QGroupBox(self.grp_init)
        self.grp_box_sa_info.setMinimumSize(QtCore.QSize(530, 100))
        self.grp_box_sa_info.setMaximumSize(QtCore.QSize(530, 100))
        self.grp_box_sa_info.setObjectName("grp_box_sa_info")
        self.gridLayout = QtGui.QGridLayout(self.grp_box_sa_info)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_temp = QtGui.QLabel(self.grp_box_sa_info)
        self.lbl_temp.setObjectName("lbl_temp")
        self.gridLayout.addWidget(self.lbl_temp, 0, 0, 1, 1)
        self.lin_temp = QtGui.QLineEdit(self.grp_box_sa_info)
        self.lin_temp.setObjectName("lin_temp")
        self.gridLayout.addWidget(self.lin_temp, 0, 1, 1, 1)
        self.lbl_alpha = QtGui.QLabel(self.grp_box_sa_info)
        self.lbl_alpha.setObjectName("lbl_alpha")
        self.gridLayout.addWidget(self.lbl_alpha, 0, 2, 1, 1)
        self.lin_alpha = QtGui.QLineEdit(self.grp_box_sa_info)
        self.lin_alpha.setObjectName("lin_alpha")
        self.gridLayout.addWidget(self.lin_alpha, 0, 3, 1, 1)
        self.lbl_beta = QtGui.QLabel(self.grp_box_sa_info)
        self.lbl_beta.setObjectName("lbl_beta")
        self.gridLayout.addWidget(self.lbl_beta, 0, 4, 1, 1)
        self.lin_beta = QtGui.QLineEdit(self.grp_box_sa_info)
        self.lin_beta.setObjectName("lin_beta")
        self.gridLayout.addWidget(self.lin_beta, 0, 5, 1, 1)
        self.btn_best = QtGui.QPushButton(self.grp_box_sa_info)
        self.btn_best.setObjectName("btn_best")
        self.gridLayout.addWidget(self.btn_best, 1, 5, 1, 1)
        self.btn_plt_out = QtGui.QPushButton(self.grp_box_sa_info)
        self.btn_plt_out.setObjectName("btn_plt_out")
        self.gridLayout.addWidget(self.btn_plt_out, 1, 4, 1, 1)
        self.btn_ok = QtGui.QPushButton(self.grp_box_sa_info)
        self.btn_ok.setObjectName("btn_ok")
        self.gridLayout.addWidget(self.btn_ok, 1, 3, 1, 1)
        self.lbl_duration = QtGui.QLabel(self.grp_box_sa_info)
        self.lbl_duration.setObjectName("lbl_duration")
        self.gridLayout.addWidget(self.lbl_duration, 1, 0, 1, 1)
        self.lin_duration = QtGui.QLineEdit(self.grp_box_sa_info)
        self.lin_duration.setObjectName("lin_duration")
        self.gridLayout.addWidget(self.lin_duration, 1, 1, 1, 1)
        self.check_bx_show_label = QtGui.QCheckBox(self.grp_box_sa_info)
        self.check_bx_show_label.setObjectName("check_bx_show_label")
        self.gridLayout.addWidget(self.check_bx_show_label, 1, 2, 1, 1)
        self.gridLayout_2.addWidget(self.grp_box_sa_info, 1, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.grp_out.setTitle(QtGui.QApplication.translate("MainWindow", "Output", None, QtGui.QApplication.UnicodeUTF8))
        self.grp_box_FP_info.setTitle(QtGui.QApplication.translate("MainWindow", "Floorplan Information", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_utilize.setText(QtGui.QApplication.translate("MainWindow", "Utilization", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_time.setText(QtGui.QApplication.translate("MainWindow", "Time", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_area.setText(QtGui.QApplication.translate("MainWindow", "Area", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_ar_ratio.setText(QtGui.QApplication.translate("MainWindow", "Aspect Ratio", None, QtGui.QApplication.UnicodeUTF8))
        self.grpbox_fp_sols.setTitle(QtGui.QApplication.translate("MainWindow", "Solution Browser", None, QtGui.QApplication.UnicodeUTF8))
        self.grp_init.setTitle(QtGui.QApplication.translate("MainWindow", "Initial Input", None, QtGui.QApplication.UnicodeUTF8))
        self.grpbox_fp.setTitle(QtGui.QApplication.translate("MainWindow", "Floorplan", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_inp_file.setText(QtGui.QApplication.translate("MainWindow", "Input File", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_inp_file.setText(QtGui.QApplication.translate("MainWindow", "Choose File", None, QtGui.QApplication.UnicodeUTF8))
        self.grp_box_sa_info.setTitle(QtGui.QApplication.translate("MainWindow", "Simulated Annealing Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_temp.setText(QtGui.QApplication.translate("MainWindow", "Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_alpha.setText(QtGui.QApplication.translate("MainWindow", "Alpha(<1)", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_beta.setText(QtGui.QApplication.translate("MainWindow", "Beta(<1)", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_best.setText(QtGui.QApplication.translate("MainWindow", "Best Solution", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_plt_out.setText(QtGui.QApplication.translate("MainWindow", "Plot Output", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_ok.setText(QtGui.QApplication.translate("MainWindow", "Start SA", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_duration.setText(QtGui.QApplication.translate("MainWindow", "Max Duration", None, QtGui.QApplication.UnicodeUTF8))
        self.check_bx_show_label.setText(QtGui.QApplication.translate("MainWindow", "Show Label", None, QtGui.QApplication.UnicodeUTF8))

